### ISSUE TITLE
Question: is memo() really needed? (it is systematically used in the README examples)

### ISSUE THREAD

**Issue by danielweck** [luncheon/preact-shared-state-hook#1]
Given that the Preact functional components in the README examples do not take any props (they only leverage local/global state), I was wondering whether the sample code should be more "minimal". Also, `memo()` has performance tradeoffs with some types of components hierarchy, it is not necessarily a guaranteed performance win.

So my question is: is `memo()` needed strictly-speaking when using `preact-shared-state-hook` to manage local/global state, or is this just for "good practice"?

Thank you :)

**Comment by luncheon** [comment]
Thank you for the good question. Here's my opinion.

Basically, I think components using `preact-shared-state-hook` should be wrapped by `memo()`.
Please see the following example. (`preact-shared-state-hook` is not used)

```tsx
import { h, render, Fragment } from "preact";
import { useState } from "preact/hooks";
import { memo } from "preact/compat";

const A = () => {
  console.log("A");
  return <div>A</div>;
};

const B = memo(() => {
  console.log("B");
  return <div>B</div>;
});

const App = () => {
  const [count, setCount] = useState(0);
  return (
    <Fragment>
      <A />
      <B />
      <button type="button" onClick={() => setCount((c) => c + 1)}>
        {count}
      </button>
    </Fragment>
  );
};

render(<App />, document.body.appendChild(document.createElement("main")));
```

https://codesandbox.io/s/rf86m

`B` is wrapped by `memo()`. `A` is not.
When the button is clicked, `"A"` is output to the console. `"B"` is not.
`B` is GC friendly because it never creates a VDOM again.

So, `memo()` is effective especially for components that do not have `props`.

If `preact-shared-state-hook` is used with `memo()`, VDOM is recreated ONLY when the state is changed. It is so efficient.

FYI, MobX with React ([mobx-react](https://github.com/mobxjs/mobx-react) and [mobx-react-lite](https://github.com/mobxjs/mobx-react-lite)) `observer` automatically wraps components with `React.memo()`.

**Comment by danielweck** [comment]
Thank you, I appreciate your insights.
I use Preact 10 and MobX 6 (via `preact/compat` bindings) in a "pet project", so I am indeed famliar with `observe()` and `memo()`.
Do you have any future plans / ambitions for `preact-shared-state-hook` (in terms of functional scope, unit testing, etc.), or is this just a demonstration of minimalism? (which of course has merit in its own rights :) )
Thanks!

**Comment by luncheon** [comment]
I see that you are familiar with `memo()`, which is why you find it unnecessary in this README case. You're right, this is just for "good practice".

I would like to keep this package very small. So it may stay like this forever.
But perhaps following features could be added (if I  have a good implementation idea).

- a feature like `autorun()`
- a feature like `computed()`

But I'm sorry, I'm fickle and lazy. (Currently I'm interested in [Solid](https://github.com/ryansolid/solid).)

Thank you.

**Comment by danielweck** [comment]
I have been following SolidJS as well, but only superficially (I haven't experimented with it yet).
